# Schema for the YouTube Plus module display settings.
youtube_plus.settings:
  type: config_object
  label: 'YouTube Plus settings'
  mapping:
    api_key:
      type: string
    channels:
      type: sequence
      sequence:
        type: mapping
        mapping:
          channel_id:
            type: string
          type:
            type: bool
