label: Cupones
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        code:
          label: Código
          separator: ', '
        usage_limit:
          label: Uso
          separator: ', '
        usage_limit_customer:
          label: 'Límite por cliente'
          separator: ', '
        operations:
          label: Operations
      filters:
        code:
          expose:
            label: Código
      title: Cupones
      arguments:
        promotion_id:
          exception:
            title: All
  page_1:
    display_title: Page
