label: Pedidos
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
      fields:
        order_number:
          separator: ', '
        placed:
          label: Date
          separator: ', '
        type:
          label: Type
          separator: ', '
        store_id:
          label: Tienda
          separator: ', '
        uid:
          label: Cliente
          separator: ', '
        mail:
          label: 'Correo electrónico'
          separator: ', '
        state:
          label: Estado
          separator: ', '
        total_price__number:
          label: Total
          separator: ', '
        operations:
          label: Operations
      filters:
        order_number:
          expose:
            label: 'Número de pedido'
        type:
          expose:
            label: Type
        state:
          expose:
            label: Estado
      title: Pedidos
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Pedidos
      tab_options:
        title: Pedidos
        description: 'Gestione sus pedidos.'
