label: 'Biblioteca de medios'
description: 'Buscar y administrar medios.'
display:
  default:
    display_title: Default
    display_options:
      title: Multimedia
      fields:
        media_bulk_form:
          action_title: Action
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: 'Aplicar filtros'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'No hay medios disponibles.'
      sorts:
        created:
          expose:
            label: 'Más recientes primero'
        name:
          expose:
            label: 'Nombre (A-Z)'
        name_1:
          expose:
            label: 'Nombre (Z-A)'
      filters:
        status:
          expose:
            label: 'Estado de publicación'
          group_info:
            label: Published
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        name:
          expose:
            label: Name
        bundle:
          expose:
            label: 'Tipos multimedia'
          group_info:
            label: 'Tipos multimedia'
        langcode:
          expose:
            label: Language
  page:
    display_title: Page
    display_options:
      fields:
        media_bulk_form:
          action_title: Action
        name:
          separator: ', '
        edit_media:
          alter:
            text: 'Editar {{ nombre }}'
            alt: 'Editar {{ nombre }}'
          text: Editar
        delete_media:
          alter:
            text: 'Borrar {{ nombre }}'
            alt: 'Borrar {{ nombre }}'
          text: Eliminar
  widget:
    display_title: Control
    display_options:
      arguments:
        bundle:
          exception:
            title: All
      filters:
        name:
          expose:
            label: Name
      header:
        display_link_grid:
          label: Cuadrícula
        display_link_table:
          label: Tabla
  widget_table:
    display_title: 'Widget (tabla)'
    display_options:
      fields:
        thumbnail__target_id:
          label: Miniatura
        name:
          label: Name
        uid:
          label: Author
        changed:
          label: Updated
      arguments:
        bundle:
          exception:
            title: All
      filters:
        name:
          expose:
            label: Name
      header:
        display_link_grid:
          label: Cuadrícula
        display_link_table:
          label: Tabla
