label: Tiendas
display:
  default:
    display_title: Máster
    display_options:
      title: Tiendas
      fields:
        is_default:
          label: Default
          separator: ', '
        name:
          label: Name
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        type:
          label: Type
          separator: ', '
        operations:
          label: Operations
      pager:
        options:
          tags:
            next: 'next ›'
            previous: '‹ previous'
            first: '« first'
            last: 'last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        type:
          expose:
            label: Type
  page_1:
    display_title: Page
