label: Perfiles
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      arguments:
        uid:
          exception:
            title: All
        type:
          exception:
            title: All
        status:
          exception:
            title: All
      title: Perfiles
  user_page:
    display_title: 'Página del usuario'
