label: 'Elementos de la orden'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        title:
          label: Title
          separator: ', '
        unit_price__number:
          label: 'Precio unitario'
          separator: ', '
        quantity:
          label: Cantidad
          separator: ', '
        total_price__number:
          label: 'Precio total'
          separator: ', '
      arguments:
        order_item_id:
          exception:
            title: All
