label: Pagos
display:
  default:
    display_title: Default
    display_options:
      title: Pagos
      fields:
        amount__number:
          label: Pago
          separator: ', '
        refunded_amount__number:
          label: 'Reembolsado:'
          separator: ', '
        avs_response_code_label:
          separator: ', '
        avs_response_code:
          label: 'Código de respuesta AVS'
          separator: ', '
        state:
          label: Estado
          separator: ', '
        payment_gateway:
          label: 'Pasarela de pago'
          separator: ', '
        authorized:
          label: Autorizado
          separator: ', '
        completed:
          label: Completado
          separator: ', '
        remote_id:
          label: 'ID remoto'
          separator: ', '
        operations:
          label: Operations
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      arguments:
        order_id:
          exception:
            title: All
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Pagos
