label: Promociones
display:
  default:
    display_title: Default
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        name:
          label: Name
          separator: ', '
        offer__target_plugin_id:
          label: 'Tipo de oferta'
          separator: ', '
        usage_limit:
          label: Uso
          separator: ', '
        usage_limit_customer:
          separator: ', '
        start_date:
          label: 'Fecha de inicio'
          separator: ', '
        end_date:
          label: 'Fecha final'
          separator: ', '
        operations:
          label: Operations
      filters:
        name:
          expose:
            label: Name
        offer__target_plugin_id:
          expose:
            label: 'Tipo de oferta'
        code:
          expose:
            label: 'Código del cupón'
        status:
          expose:
            label: Status
      title: Promociones
  admin:
    display_title: Page
    display_options:
      menu:
        title: List
      tab_options:
        title: List
